version: 2
jobs:
  build:
    docker:
      - image: maven:3-jdk-8
       # Descomentar quando precisar de servico disponivel (em background)
#      - image: tomcat:9-jdk11
    working_directory: ~/java-circleci-kubernetes-example
    steps:
      - checkout
      - run:
          name: Build and Run tests
          command: mvn install

  deploy:
    docker:
      - image: tomcat:9-jdk11
    working_directory: ~/java-circleci-kubernetes-example
    steps:
      - checkout
      - run:
          name: Setup
          command: echo SETUP
      - run:
          name: Deploy
          command: echo SETUP

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

