version: 2
jobs:
  build:
    docker:
      - image: maven:3-jdk-8
       # Descomentar quando precisar de servico disponivel (em background)
#      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run:
          name: Build and Run tests
          command: rake

  deploy:
    machine:
        enabled: true
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run:
          name: Setup
          command: echo SETUP
      - run:
          name: Deploy
          command: echo SETUP

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

