version: 2
jobs:
  build:
    docker:
      - image: maven:3-jdk-8
       # Descomentar quando precisar de servico disponivel (em background)
#      - image: tomcat:9-jdk11
    working_directory: ~/java-circleci-kubernetes-example
    steps:
      - checkout
      - restore_cache:
         keys:
           - m2-{{ checksum "pom.xml" }}
      - run:
          name: Build and Run tests
          command: mvn install
      - save_cache:
          key: m2-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

  deploy:
    docker:
      - image: tomcat:9-jdk11
    working_directory: ~/java-circleci-kubernetes-example
    steps:
      - checkout
      - restore_cache:
         keys:
           - m2-{{ checksum "pom.xml" }}
      - run:
          name: Setup
          command: echo SETUP
      - run:
          name: Deploy
          command: echo SETUP
      - save_cache:
          key: m2-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

