version: 2.1
orbs:
  docker: circleci/docker@0.5.8

jobs:
  build:
    docker:
      - image: maven:3-jdk-8
       # Descomentar quando precisar de servico disponivel (em background)
#      - image: openjdk:12-jdk-oracle
    working_directory: ~/java-circleci-kubernetes-example
    steps:
      - checkout
      - restore_cache:
         keys:
           - m2-{{ checksum "pom.xml" }}
      - run:
          name: Build and Run tests
          command: mvn install
      - save_cache:
          key: m2-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2
      - store_artifacts:
          path: ~/java-circleci-kubernetes-example/java-cicd-0.0.1-SNAPSHOT.jar
          destination: /var/tmp/java-cicd-0.0.1-SNAPSHOT.jar

  dockerize:
    executor: docker/machine
    working_directory: ~/java-circleci-kubernetes-example
    steps:
      - checkout
      - run: cp -iv /var/tmp/*.jar docker/
      - docker/build:
          path: docker/

  deploy:
    docker:
      - image: tomcat:9-jdk11
    working_directory: ~/java-circleci-kubernetes-example
    steps:
      - checkout
      - restore_cache:
         keys:
           - m2-{{ checksum "pom.xml" }}
      - run:
          name: Setup
          command: echo SETUP
      - run:
          name: Deploy
          command: echo SETUP
      - save_cache:
          key: m2-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build
      - dockerize:
          requires:
            - build
      - deploy:
          requires:
            - dockerize

