version: 2.1
orbs:
  docker: circleci/docker@0.5.8

jobs:
  build:
    docker:
      - image: maven:3-jdk-8
       # Descomentar quando precisar de servico disponivel (em background)
#      - image: openjdk:12-jdk-oracle
    working_directory: ~/java-circleci-kubernetes-example
    steps:
      - checkout
      - restore_cache:
         keys:
           - m2-{{ checksum "pom.xml" }}
      - run:
          name: Build and Run tests
          command: mvn install
      - store_artifacts:
          path: ~/java-circleci-kubernetes-example/java-cicd-0.0.1-SNAPSHOT.jar
          destination: /var/tmp/java-cicd.jar
      - save_cache:
          key: m2-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2
            - /var/tmp/java-cicd.jar

  dockerize:
    executor: docker/machine
    working_directory: ~/java-circleci-kubernetes-example
    steps:
      - checkout
      - restore_cache:
         keys:
           - m2-{{ checksum "pom.xml" }}
      - run:
         name: Prepare to make Application part of a Docker image
         command: ls -l /var/tmp/ && cp -iv /var/tmp/java-cicd.jar docker/
      - docker/install-docker
      - docker/build:
          path: docker/
          image: andrecsouza/application:${CIRCLE_BUILD_NUM}
      - run:
         name: Run Docker image
         command: docker run -it -d --network=host andrecsouza/application:${CIRCLE_BUILD_NUM}
      - run:
         name: Invoke health endpoint
         command: sleep 10s && curl http://localhost:8080/actuator

  deploy:
    docker:
      - image: tomcat:9-jdk11
    working_directory: ~/java-circleci-kubernetes-example
    steps:
      - checkout
      - restore_cache:
         keys:
           - m2-{{ checksum "pom.xml" }}
      - run:
          name: Setup
          command: echo SETUP
      - run:
          name: Deploy
          command: echo SETUP
      - save_cache:
          key: m2-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

workflows:
  build-and-deploy:
    jobs:
      - build
      - dockerize:
          requires:
            - build
      - deploy:
          requires:
            - dockerize

